### ISSUE TITLE
Run outside of VS

### ISSUE THREAD

**Issue by kostenickj** [TheRealMJP/Shadows#3]
Hello!
This might be a dumb question but i cannot figure out how to get this to run outside of VS.  When i run Shadows.exe i get this error.

![image](https://user-images.githubusercontent.com/17304343/61315358-74149000-a7b3-11e9-9c7e-e974086da407.png)

It runs fine when debugging inside visual studio. I also tried putting the AntWeakBar64.dll in the same folder as the exe. I gets past that error but just crashes.

Any help is appreciated, and thanks!

**Comment by TheRealMJP** [comment]
Hey Jacob, this is not a dumb question at all. Really it's the result of some poor decisions and laziness on my part. Your easiest route to making this work would be to to build the solution, then copy Shadows.exe to the same directory as the vcxproj file. This will make sure that the DLL's are side by side with the exe, and will keep the program from complaining about finding files (it assumes that the current directory is the vcxproj root). I've fixed a few of these things in later samples, but I never got around to back-porting them to this one. I guess I should at some point! 😄
